closed_chain:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------

  closed_chain_right_pad_joint1_controller:
    type: effort_controllers/JointPositionController
    joint: closed_chain_right_pad_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}


