
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Position Controllers ---------------------------------------

joint2_controller:
  type: effort_controllers/JointPositionController
  joint: right_pad2_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}


