

ginko:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  leg_l_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg_l_joint1
    pid: {p: 100.0, i: 0.0, d: 0.0}
  leg_l_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg_l_joint4
    pid: {p: 100.0, i: 0.0, d: 0.0}
  leg_l_joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg_l_joint7
    pid: {p: 100.0, i: 0.0, d: 0.0}
  leg_l_joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg_l_joint8
    pid: {p: 100.0, i: 0.0, d: 0.0}